#!/usr/bin/env zsh

sudo apt install build-essential python3-dev

# install Vundle plugin manager
git clone https://github.com/VundleVim/Vundle.vim.git ./nvim/.config/nvim/bundle/Vundle.vim

# install vim-plug
#curl -fLo ~/.var/app/io.neovim.nvim/data/nvim/site/autoload/plug.vim --create-dirs \
#   https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

nvim +'PlugInstall --sync' +qa

pushd $HOME/.vim/bundle/YouCompleteMe
python3 install.py --clangd-completer
popd

#for copilot we need to install node js 12 or superior
curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
sudo apt-get install -y nodejs
