#! /bin/sh


pgrep -x shxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d VI VII VIII IX X
bspc monitor HDMI-0 -d I II III IV V 

$HOME/.config/polybar/launch.sh &
# $HOME/.config/polybar-collection/launch.sh &
feh --bg-scale $HOME/.config/wallpaper/wallpaper.jpg &


bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
