#!/bin/bash

#aliases

alias resource='source ~/.bashrc'
alias vim='nvim'

# powerline setup

PATH=${PATH}:$HOME/.local/bin

powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
POWERLINE_DIR=$(pip show powerline-status | grep Location | cut -d' ' -f2)

. ${POWERLINE_DIR}/powerline/bindings/bash/powerline.sh

# HSTR configuration - add this to ~/.bashrc
alias hh=hstr                    # hh to be alias for hstr
# color with bottom bar 
export HSTR_CONFIG=hicolor,prompt-bottom,help-on-opposite-side
shopt -s histappend              # append new history items to .bash_history
export HISTCONTROL=ignorespace   # leading space hides commands from history
export HISTFILESIZE=10000        # increase history file size (default is 500)
export HISTSIZE=${HISTFILESIZE}  # increase history size (default is 500)
# ensure synchronization between bash memory and history file
export PROMPT_COMMAND="history -a; history -n; ${PROMPT_COMMAND}"
function hstrnotiocsti {
    { READLINE_LINE="$( { </dev/tty hstr ${READLINE_LINE}; } 2>&1 1>&3 3>&- )"; } 3>&1;
    READLINE_POINT=${#READLINE_LINE}
}
# if this is interactive shell, then bind hstr to Ctrl-r (for Vi mode check doc)
if [[ $- =~ .*i.* ]]; then bind -x '"\C-r": "hstrnotiocsti"'; fi
export HSTR_TIOCSTI=n



